jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Event triggerd from [${{ github.event_name }}]"
          echo "Branch name is [${{ github.ref }}] and repo is [.]"

      - uses: actions/checkout@v3.3.0

      - name: List files in the repository
        run: |
          echo "Files in Repo [${{ github.repository }}]:"
          tree
